### ISSUE TITLE
Page without a set visitor cookie

### ISSUE THREAD

**Issue by yifan9916** [Scout24/toguru-client-nodejs#4]
#### Problem

When landing on a page where the `as24visitor` cookie is not set, toguru will throw an error, thus causing whatever is behind the feature toggle to not be sent to the client. Other services/fragments included on the page which do set the cookie, do not solve the issue and **_it has to be set by the page itself_**. When the cookie is carried over from other pages which do set the cookie, the issue is resolved.

#### Case

Static pages such as the [auto catalog](https://www.autoscout24.de/auto/audi/audi-r8/) do not set the required cookie for toguru, which causes a fragment to not show up. Organic traffic from _new AS24 users, who have never visited another page,_ does not display the fragment.

**Comment by omakoleg** [comment]
Happens also for me.
```
{"level":50,"pid":7,"hostname":"...","message":"Cannot read property 'replace' of null","stack":"TypeError: Cannot read property 'replace' of null\n    
at module.exports (/app/node_modules/toguru-client/src/calculate-bucket.js:4:38)\n    
at Object.isToggleEnabled (/app/node_modules/toguru-client/src/client.js:24:28)\n    
at Object.isToggleEnabled (/app/node_modules/toguru-client/src/express-middleware.js:43:57)\n    
at router.get (/app/src/routes/admin.js:156:5)\n    
at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)\n   
 at next (/app/node_modules/express/lib/router/route.js:137:13)\n    
at /app/node_modules/toguru-client/src/express-middleware.js:52:13\n    
at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)","url":"....","status":500,"v":1}
```

**Comment by yifan9916** [comment]
@omakoleg the fix is on a branch. @bdadam still hasn't come around to merge it. by coming friday at latest

**Comment by omakoleg** [comment]
So far I am injecting cookie before toguruClient middleware if it was not set.
