### ISSUE TITLE
Failing on some uuid values in user cookie

### ISSUE THREAD

**Issue by omakoleg** [Scout24/toguru-client-nodejs#7]
```
"Cannot mix BigInt and other types, use explicit conversions","stack":"TypeError: Cannot mix BigInt and other types, use explicit conversions\n    at Object.<anonymous>.module.exports (/Users/omakiienko/projects/dealer-info-admin/node_modules/toguru-client/src/calculate-bucket.js:5:28)\n    at Object.isToggleEnabled (/Users/omakiienko/projects/dealer-info-admin/node_modules/toguru-client/src/client.js:24:28)\n    at Object.isToggleEnabled (/Users/omakiienko/projects/dealer-info-admin/node_modules/toguru-client/src/express-middleware.js:43:57)
```
Failing Not all time, but to reproduce set random `uuid()` value into cookie.

**Comment by omakoleg** [comment]
Not latest version affected. Recent is fine
